/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppSuppliersSupplierIdRouteImport } from './routes/_app.suppliers_.$supplierId'
import { Route as AppProductsProductIdRouteImport } from './routes/_app.products_.$productId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app.customers_.$customerId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersSupplierIdRoute = AppSuppliersSupplierIdRouteImport.update({
  id: '/suppliers_/$supplierId',
  path: '/suppliers/$supplierId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/customers': typeof AppCustomersRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/customers': typeof AppCustomersRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/stock': typeof AppStockRoute
  '/suppliers': typeof AppSuppliersRoute
  '/': typeof AppIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/suppliers/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stock': typeof AppStockRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers_/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/products_/$productId': typeof AppProductsProductIdRoute
  '/_app/suppliers_/$supplierId': typeof AppSuppliersSupplierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/customers'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/suppliers/$supplierId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/customers'
    | '/products'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/'
    | '/customers/$customerId'
    | '/products/$productId'
    | '/suppliers/$supplierId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/customers'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/stock'
    | '/_app/suppliers'
    | '/_app/'
    | '/_app/customers_/$customerId'
    | '/_app/products_/$productId'
    | '/_app/suppliers_/$supplierId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers_/$supplierId': {
      id: '/_app/suppliers_/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AppSuppliersSupplierIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products_/$productId': {
      id: '/_app/products_/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers_/$customerId': {
      id: '/_app/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockRoute: typeof AppStockRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppSuppliersSupplierIdRoute: typeof AppSuppliersSupplierIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockRoute: AppStockRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppSuppliersSupplierIdRoute: AppSuppliersSupplierIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
